# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'myStressTestServerPort.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form_StressTestServerPort(object):
    def setupUi(self, Form_StressTestServerPort):
        Form_StressTestServerPort.setObjectName("Form_StressTestServerPort")
        Form_StressTestServerPort.resize(820, 598)
        self.tabWidget = QtWidgets.QTabWidget(Form_StressTestServerPort)
        self.tabWidget.setGeometry(QtCore.QRect(360, 40, 451, 531))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 431, 61))
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 20, 137, 25))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.pushButton_openRecord = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_openRecord.setObjectName("pushButton_openRecord")
        self.horizontalLayout_8.addWidget(self.pushButton_openRecord)
        self.label_MsgCount = QtWidgets.QLabel(self.layoutWidget)
        self.label_MsgCount.setText("")
        self.label_MsgCount.setObjectName("label_MsgCount")
        self.horizontalLayout_8.addWidget(self.label_MsgCount)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 80, 431, 431))
        self.groupBox_2.setObjectName("groupBox_2")
        self.pushButton_addTask = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_addTask.setGeometry(QtCore.QRect(180, 400, 75, 23))
        self.pushButton_addTask.setObjectName("pushButton_addTask")
        self.tableWidget_desServer = QtWidgets.QTableWidget(self.groupBox_2)
        self.tableWidget_desServer.setGeometry(QtCore.QRect(10, 170, 411, 211))
        self.tableWidget_desServer.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget_desServer.setObjectName("tableWidget_desServer")
        self.tableWidget_desServer.setColumnCount(4)
        self.tableWidget_desServer.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_desServer.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(9)
        item.setFont(font)
        self.tableWidget_desServer.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_desServer.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_desServer.setHorizontalHeaderItem(3, item)
        self.tableWidget_desServer.horizontalHeader().setVisible(False)
        self.tableWidget_desServer.verticalHeader().setVisible(False)
        self.line = QtWidgets.QFrame(self.groupBox_2)
        self.line.setGeometry(QtCore.QRect(10, 380, 411, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.layoutWidget1 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget1.setGeometry(QtCore.QRect(20, 20, 137, 22))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.comboBox_projecet = QtWidgets.QComboBox(self.layoutWidget1)
        self.comboBox_projecet.setObjectName("comboBox_projecet")
        self.horizontalLayout.addWidget(self.comboBox_projecet)
        self.layoutWidget2 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget2.setGeometry(QtCore.QRect(20, 50, 201, 22))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.lineEdit_totalUsers = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_totalUsers.setObjectName("lineEdit_totalUsers")
        self.horizontalLayout_2.addWidget(self.lineEdit_totalUsers)
        self.layoutWidget3 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget3.setGeometry(QtCore.QRect(20, 80, 131, 22))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.layoutWidget3)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.lineEdit_onceUsers = QtWidgets.QLineEdit(self.layoutWidget3)
        self.lineEdit_onceUsers.setObjectName("lineEdit_onceUsers")
        self.horizontalLayout_3.addWidget(self.lineEdit_onceUsers)
        self.layoutWidget4 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget4.setGeometry(QtCore.QRect(160, 80, 131, 22))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.lineEdit_spaceTime = QtWidgets.QLineEdit(self.layoutWidget4)
        self.lineEdit_spaceTime.setObjectName("lineEdit_spaceTime")
        self.horizontalLayout_4.addWidget(self.lineEdit_spaceTime)
        self.layoutWidget5 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget5.setGeometry(QtCore.QRect(20, 140, 224, 25))
        self.layoutWidget5.setObjectName("layoutWidget5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.layoutWidget5)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget5)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_5.addWidget(self.label_4)
        self.pushButton_addServer = QtWidgets.QPushButton(self.layoutWidget5)
        self.pushButton_addServer.setObjectName("pushButton_addServer")
        self.horizontalLayout_5.addWidget(self.pushButton_addServer)
        self.pushButton_deleteServer = QtWidgets.QPushButton(self.layoutWidget5)
        self.pushButton_deleteServer.setObjectName("pushButton_deleteServer")
        self.horizontalLayout_5.addWidget(self.pushButton_deleteServer)
        self.layoutWidget6 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget6.setGeometry(QtCore.QRect(180, 20, 137, 22))
        self.layoutWidget6.setObjectName("layoutWidget6")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.layoutWidget6)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_8 = QtWidgets.QLabel(self.layoutWidget6)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_7.addWidget(self.label_8)
        self.comboBox_env = QtWidgets.QComboBox(self.layoutWidget6)
        self.comboBox_env.setObjectName("comboBox_env")
        self.horizontalLayout_7.addWidget(self.comboBox_env)
        self.layoutWidget7 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget7.setGeometry(QtCore.QRect(21, 110, 219, 22))
        self.layoutWidget7.setObjectName("layoutWidget7")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.layoutWidget7)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget7)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        self.comboBox_loopType = QtWidgets.QComboBox(self.layoutWidget7)
        self.comboBox_loopType.setObjectName("comboBox_loopType")
        self.comboBox_loopType.addItem("")
        self.comboBox_loopType.addItem("")
        self.comboBox_loopType.addItem("")
        self.horizontalLayout_6.addWidget(self.comboBox_loopType)
        self.checkBox_ignoreErr = QtWidgets.QCheckBox(self.layoutWidget7)
        self.checkBox_ignoreErr.setObjectName("checkBox_ignoreErr")
        self.horizontalLayout_6.addWidget(self.checkBox_ignoreErr)
        self.tabWidget.addTab(self.tab, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_6)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 10, 421, 161))
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_9 = QtWidgets.QLabel(self.groupBox_3)
        self.label_9.setGeometry(QtCore.QRect(10, 20, 54, 12))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.groupBox_3)
        self.label_10.setGeometry(QtCore.QRect(130, 20, 54, 12))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.groupBox_3)
        self.label_11.setGeometry(QtCore.QRect(270, 20, 54, 12))
        self.label_11.setObjectName("label_11")
        self.label_errtotal = QtWidgets.QLabel(self.groupBox_3)
        self.label_errtotal.setGeometry(QtCore.QRect(50, 20, 54, 12))
        self.label_errtotal.setObjectName("label_errtotal")
        self.label_errconnect = QtWidgets.QLabel(self.groupBox_3)
        self.label_errconnect.setGeometry(QtCore.QRect(190, 20, 54, 12))
        self.label_errconnect.setObjectName("label_errconnect")
        self.label_timeout = QtWidgets.QLabel(self.groupBox_3)
        self.label_timeout.setGeometry(QtCore.QRect(310, 20, 54, 12))
        self.label_timeout.setObjectName("label_timeout")
        self.tabWidget.addTab(self.tab_6, "")
        self.tabWidget_2 = QtWidgets.QTabWidget(Form_StressTestServerPort)
        self.tabWidget_2.setGeometry(QtCore.QRect(10, 10, 351, 561))
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tableWidget_stressClients = QtWidgets.QTableWidget(self.tab_3)
        self.tableWidget_stressClients.setEnabled(True)
        self.tableWidget_stressClients.setGeometry(QtCore.QRect(10, 10, 331, 521))
        self.tableWidget_stressClients.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_stressClients.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget_stressClients.setColumnCount(4)
        self.tableWidget_stressClients.setObjectName("tableWidget_stressClients")
        self.tableWidget_stressClients.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.tableWidget_stressClients.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.tableWidget_stressClients.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.tableWidget_stressClients.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_stressClients.setHorizontalHeaderItem(3, item)
        self.tableWidget_stressClients.horizontalHeader().setVisible(True)
        self.tableWidget_stressClients.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget_stressClients.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget_stressClients.horizontalHeader().setStretchLastSection(False)
        self.tableWidget_stressClients.verticalHeader().setVisible(False)
        self.tableWidget_stressClients.verticalHeader().setCascadingSectionResizes(False)
        self.tabWidget_2.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tableWidget_proxyClients = QtWidgets.QTableWidget(self.tab_4)
        self.tableWidget_proxyClients.setGeometry(QtCore.QRect(10, 10, 331, 521))
        self.tableWidget_proxyClients.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_proxyClients.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget_proxyClients.setObjectName("tableWidget_proxyClients")
        self.tableWidget_proxyClients.setColumnCount(3)
        self.tableWidget_proxyClients.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.tableWidget_proxyClients.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.tableWidget_proxyClients.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.tableWidget_proxyClients.setHorizontalHeaderItem(2, item)
        self.tabWidget_2.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.tableWidget_recordlists = QtWidgets.QTableWidget(self.tab_5)
        self.tableWidget_recordlists.setGeometry(QtCore.QRect(10, 10, 331, 521))
        self.tableWidget_recordlists.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_recordlists.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget_recordlists.setObjectName("tableWidget_recordlists")
        self.tableWidget_recordlists.setColumnCount(3)
        self.tableWidget_recordlists.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.tableWidget_recordlists.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.tableWidget_recordlists.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.tableWidget_recordlists.setHorizontalHeaderItem(2, item)
        self.tabWidget_2.addTab(self.tab_5, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tableWidget_Tasks = QtWidgets.QTableWidget(self.tab_2)
        self.tableWidget_Tasks.setGeometry(QtCore.QRect(10, 10, 331, 521))
        self.tableWidget_Tasks.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_Tasks.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget_Tasks.setObjectName("tableWidget_Tasks")
        self.tableWidget_Tasks.setColumnCount(3)
        self.tableWidget_Tasks.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.tableWidget_Tasks.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.tableWidget_Tasks.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Tasks.setHorizontalHeaderItem(2, item)
        self.tabWidget_2.addTab(self.tab_2, "")
        self.label_7 = QtWidgets.QLabel(Form_StressTestServerPort)
        self.label_7.setGeometry(QtCore.QRect(10, 580, 351, 16))
        self.label_7.setOpenExternalLinks(True)
        self.label_7.setObjectName("label_7")
        self.widget = QtWidgets.QWidget(Form_StressTestServerPort)
        self.widget.setGeometry(QtCore.QRect(400, 10, 414, 27))
        self.widget.setObjectName("widget")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit_stressClient_addr = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_stressClient_addr.setObjectName("lineEdit_stressClient_addr")
        self.gridLayout.addWidget(self.lineEdit_stressClient_addr, 0, 0, 1, 1)
        self.pushButton_stressClientRun = QtWidgets.QPushButton(self.widget)
        self.pushButton_stressClientRun.setObjectName("pushButton_stressClientRun")
        self.gridLayout.addWidget(self.pushButton_stressClientRun, 0, 1, 1, 1)
        self.horizontalLayout_10.addLayout(self.gridLayout)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_12 = QtWidgets.QLabel(self.widget)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_9.addWidget(self.label_12)
        self.comboBox_loglevel = QtWidgets.QComboBox(self.widget)
        self.comboBox_loglevel.setObjectName("comboBox_loglevel")
        self.horizontalLayout_9.addWidget(self.comboBox_loglevel)
        self.horizontalLayout_10.addLayout(self.horizontalLayout_9)

        self.retranslateUi(Form_StressTestServerPort)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form_StressTestServerPort)

    def retranslateUi(self, Form_StressTestServerPort):
        _translate = QtCore.QCoreApplication.translate
        Form_StressTestServerPort.setWindowTitle(_translate("Form_StressTestServerPort", "Sheeps 控制端 - 卢天明 - QQ641471957"))
        self.groupBox.setTitle(_translate("Form_StressTestServerPort", "录制"))
        self.pushButton_openRecord.setText(_translate("Form_StressTestServerPort", "启动录制"))
        self.groupBox_2.setTitle(_translate("Form_StressTestServerPort", "回放"))
        self.pushButton_addTask.setText(_translate("Form_StressTestServerPort", "添加任务"))
        item = self.tableWidget_desServer.horizontalHeaderItem(0)
        item.setText(_translate("Form_StressTestServerPort", "录制IP"))
        item = self.tableWidget_desServer.horizontalHeaderItem(1)
        item.setText(_translate("Form_StressTestServerPort", "录制Port"))
        item = self.tableWidget_desServer.horizontalHeaderItem(2)
        item.setText(_translate("Form_StressTestServerPort", "重放IP"))
        item = self.tableWidget_desServer.horizontalHeaderItem(3)
        item.setText(_translate("Form_StressTestServerPort", "重放Port"))
        self.label_5.setText(_translate("Form_StressTestServerPort", "项    目："))
        self.label_2.setText(_translate("Form_StressTestServerPort", "用户总数："))
        self.label.setText(_translate("Form_StressTestServerPort", "单次数量："))
        self.label_3.setText(_translate("Form_StressTestServerPort", "间隔(秒)："))
        self.label_4.setText(_translate("Form_StressTestServerPort", "回放端口："))
        self.pushButton_addServer.setText(_translate("Form_StressTestServerPort", "增加"))
        self.pushButton_deleteServer.setText(_translate("Form_StressTestServerPort", "删除"))
        self.label_8.setText(_translate("Form_StressTestServerPort", "测试环境："))
        self.label_6.setText(_translate("Form_StressTestServerPort", "循环模式："))
        self.comboBox_loopType.setItemText(0, _translate("Form_StressTestServerPort", "循环"))
        self.comboBox_loopType.setItemText(1, _translate("Form_StressTestServerPort", "不循环"))
        self.comboBox_loopType.setItemText(2, _translate("Form_StressTestServerPort", "实时回放"))
        self.checkBox_ignoreErr.setText(_translate("Form_StressTestServerPort", "忽略错误"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form_StressTestServerPort", "录制和回放"))
        self.groupBox_3.setTitle(_translate("Form_StressTestServerPort", "错误"))
        self.label_9.setText(_translate("Form_StressTestServerPort", "总数："))
        self.label_10.setText(_translate("Form_StressTestServerPort", "连接失败："))
        self.label_11.setText(_translate("Form_StressTestServerPort", "超时："))
        self.label_errtotal.setText(_translate("Form_StressTestServerPort", "0"))
        self.label_errconnect.setText(_translate("Form_StressTestServerPort", "0"))
        self.label_timeout.setText(_translate("Form_StressTestServerPort", "0"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("Form_StressTestServerPort", "监视器"))
        item = self.tableWidget_stressClients.horizontalHeaderItem(0)
        item.setText(_translate("Form_StressTestServerPort", "编号"))
        item = self.tableWidget_stressClients.horizontalHeaderItem(1)
        item.setText(_translate("Form_StressTestServerPort", "IP地址"))
        item = self.tableWidget_stressClients.horizontalHeaderItem(2)
        item.setText(_translate("Form_StressTestServerPort", "CPU数量"))
        item = self.tableWidget_stressClients.horizontalHeaderItem(3)
        item.setText(_translate("Form_StressTestServerPort", "状态"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), _translate("Form_StressTestServerPort", "受控端列表"))
        item = self.tableWidget_proxyClients.horizontalHeaderItem(0)
        item.setText(_translate("Form_StressTestServerPort", "编号"))
        item = self.tableWidget_proxyClients.horizontalHeaderItem(1)
        item.setText(_translate("Form_StressTestServerPort", "IP地址"))
        item = self.tableWidget_proxyClients.horizontalHeaderItem(2)
        item.setText(_translate("Form_StressTestServerPort", "PORT端口"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), _translate("Form_StressTestServerPort", "连接列表"))
        item = self.tableWidget_recordlists.horizontalHeaderItem(0)
        item.setText(_translate("Form_StressTestServerPort", "保留"))
        item = self.tableWidget_recordlists.horizontalHeaderItem(1)
        item.setText(_translate("Form_StressTestServerPort", "IP地址"))
        item = self.tableWidget_recordlists.horizontalHeaderItem(2)
        item.setText(_translate("Form_StressTestServerPort", "PORT端口"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), _translate("Form_StressTestServerPort", "录制列表"))
        item = self.tableWidget_Tasks.horizontalHeaderItem(0)
        item.setText(_translate("Form_StressTestServerPort", "编号"))
        item = self.tableWidget_Tasks.horizontalHeaderItem(1)
        item.setText(_translate("Form_StressTestServerPort", "状态"))
        item = self.tableWidget_Tasks.horizontalHeaderItem(2)
        item.setText(_translate("Form_StressTestServerPort", "说明"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_2), _translate("Form_StressTestServerPort", "任务列表"))
        self.label_7.setText(_translate("Form_StressTestServerPort", "项目地址：<a href=\"https://gitee.com/lutianming/Sheeps\">https://gitee.com/lutianming/Sheeps</a>"))
        self.lineEdit_stressClient_addr.setText(_translate("Form_StressTestServerPort", "127.0.0.1:1080"))
        self.pushButton_stressClientRun.setText(_translate("Form_StressTestServerPort", "启动本地受控端"))
        self.label_12.setText(_translate("Form_StressTestServerPort", "受控端日志等级："))

